// Datos extraídos de README, package.json e historial git de cada carpeta en 1MGactivos
export const categories = {
  web: { label: 'Web & Marca', color: '#ff4d4d' },
  marketing: { label: 'Marketing & Eventos', color: '#ffb020' },
  ops: { label: 'Operaciones & Industria', color: '#3dd6a5' },
  tools: { label: 'Herramientas Internas', color: '#5aa9ff' },
};

export const projects = [
  { id: 'site', name: 'Mi Gusto Site', emoji: '🌐', cat: 'web', start: '2025-05', end: '2026-09',
    tagline: 'WebApp gastronómica premium',
    desc: 'Sitio institucional con storytelling digital: productos, franquicias, sucursales y empleos. Experiencia visual cross-device.',
    stack: ['React', 'GSAP', 'Bootstrap', 'EmailJS', 'Mailchimp'] },
  { id: 'newcarta', name: 'New Carta Digital', emoji: '📖', cat: 'web', start: '2025-05', end: '2026-05',
    tagline: 'Plataforma de productos cross-device',
    desc: 'Evolución de la web para gestión, visualización y promoción de productos y sucursales.',
    stack: ['React', 'GSAP', 'Bootstrap'] },
  { id: 'flamin', name: "Flamin' Hot · CRUNCHY", emoji: '🔥', cat: 'marketing', start: '2025-11', end: '2026-07',
    tagline: 'Micrositio de lanzamiento',
    desc: 'Micrositio promocional para la empanada CRUNCHY con animaciones, modelo 3D, efectos visuales y medición avanzada. Live en migusto.com.ar/crunchy.',
    stack: ['React', 'Supabase', '3D'] },
  { id: 'rooms', name: 'Rooms · Reminders', emoji: '🗂️', cat: 'tools', start: '2025-11', end: '2026-02',
    tagline: 'Recordatorios compartidos por salas',
    desc: 'App interna para organizar tareas por áreas y personas, con vistas de tarjetas, calendario y diagrama de Gantt.',
    stack: ['React', 'Supabase'] },
  { id: 'legales', name: 'Legales', emoji: '⚖️', cat: 'web', start: '2026-02', end: '2026-02',
    tagline: 'Bases y condiciones',
    desc: 'Páginas legales y bases y condiciones para promociones y acciones de marca.',
    stack: ['HTML'] },
  { id: 'llamador', name: 'Llamador Lollapalooza', emoji: '📣', cat: 'ops', start: '2026-02', end: '2026-03',
    tagline: 'Llamado de pedidos offline',
    desc: 'Sistema offline para puntos de venta en Lollapalooza BA: interfaz táctil para el cajero y vista para TV vertical.',
    stack: ['React', 'Supabase', 'Offline'] },
  { id: 'games', name: 'Aperture Games', emoji: '🕹️', cat: 'marketing', start: '2026-02', end: '2026-04',
    tagline: 'Empanada Arcade',
    desc: 'Menú de juegos arcade temáticos de empanadas para aperturas de nuevos locales 2026.',
    stack: ['Phaser', 'GSAP', 'Howler'] },
  { id: 'golden', name: 'Golden Tickets', emoji: '🎫', cat: 'marketing', start: '2026-02', end: '2026-10',
    tagline: 'Mi Gusto Experience',
    desc: 'Validación de cupones, registro de ganadores y gestión de beneficios mensuales.',
    stack: ['React', 'Supabase', 'Framer Motion'] },
  { id: 'qr', name: 'QR Generator Pro', emoji: '🔳', cat: 'tools', start: '2026-02', end: '2026-08',
    tagline: 'QRs dinámicos con métricas',
    desc: 'Generador de códigos QR para campañas y locales, con gestión centralizada.',
    stack: ['React', 'TypeScript', 'Supabase'] },
  { id: 'mes', name: 'MES System', emoji: '🏭', cat: 'ops', start: '2026-03', end: '2026-05',
    tagline: 'Manufacturing Execution System',
    desc: 'Monitoreo y optimización de procesos de producción en tiempo real con dashboards.',
    stack: ['React', 'Supabase', 'Recharts'] },
  { id: 'orbital', name: 'MG Orbital', emoji: '🛰️', cat: 'ops', start: '2026-03', end: '2026-09',
    tagline: 'Digitalización industrial',
    desc: 'Ecosistema de registro de actividades: mapas, gráficos y reportes PDF para la operación.',
    stack: ['React', 'Supabase', 'Leaflet', 'Chart.js'] },
  { id: 'degu', name: 'Degustación a Puertas Cerradas', emoji: '🍷', cat: 'marketing', start: '2026-05', end: '2026-05',
    tagline: 'Registro de eventos exclusivos',
    desc: 'Experiencia cinematográfica de inscripción con múltiples turnos y control de cupos.',
    stack: ['React', 'Supabase', 'GSAP'] },
  { id: 'tech', name: 'TechControl', emoji: '💻', cat: 'tools', start: '2026-05', end: '2026-10',
    tagline: 'Gestión de activos IT',
    desc: 'Centraliza, audita y optimiza el ciclo de vida de la infraestructura tecnológica.',
    stack: ['React', 'Tailwind', 'Supabase', 'shadcn'] },
  { id: 'sagrada', name: 'Mi Gusto x La Sagrada', emoji: '✨', cat: 'marketing', start: '2026-05', end: '2026-06',
    tagline: 'Un ritual hecho para compartir',
    desc: 'Micrositio de la colaboración con La Sagrada, con estética dorada y animaciones.',
    stack: ['React', 'Supabase', 'GSAP'] },
  { id: 'carta', name: 'Carta Digital', emoji: '📱', cat: 'web', start: '2026-06', end: '2026-09',
    tagline: 'Feed de promociones',
    desc: 'Feed scrolleable de promociones con panel de administración completo.',
    stack: ['React', 'Firebase', 'Supabase', 'GSAP'] },
  { id: 'capa', name: 'Capacitaciones', emoji: '🎓', cat: 'ops', start: '2026-06', end: '2026-09',
    tagline: 'Buenas Prácticas de Manufactura',
    desc: 'Plataforma de capacitación obligatoria en BPM para el personal.',
    stack: ['React', 'TypeScript', 'Supabase'] },
  { id: 'canjes', name: 'Canjes Influencers', emoji: '🤝', cat: 'marketing', start: '2025-11', end: '2026-09',
    tagline: 'Formulario de canjes',
    desc: 'Campos dinámicos desde Supabase, interfaz tematizada y paneles de administración e historial.',
    stack: ['React', 'Supabase'] },
  { id: 'ruleta', name: 'Ruleta Bella Vista', emoji: '🎡', cat: 'marketing', start: '2026-07', end: '2026-07',
    tagline: 'Reapertura Bella Vista',
    desc: 'Los participantes completan un formulario y giran una ruleta animada para ganar premios.',
    stack: ['React', 'TypeScript', 'GSAP'] },
  { id: 'clipper', name: 'ScreenFlow · Clipper', emoji: '🎬', cat: 'tools', start: '2026-07', end: '2026-09',
    tagline: 'Grabación 100% local',
    desc: 'Grabador de pantalla con remoción de fondo en el navegador, privacidad local-first.',
    stack: ['React', 'Vite', 'IMG.LY'] },
  { id: 'audit', name: 'Audit App', emoji: '✅', cat: 'ops', start: '2026-10', end: '2026-10',
    tagline: 'Auditorías en locales',
    desc: 'Nuevo proyecto: app para auditorías operativas en sucursales.',
    stack: ['React'] },
  // ⚠️ Proyectos sin carpeta en 1MGactivos: fechas, textos y stack PROVISORIOS
  { id: 'copa', name: 'Copa Mundial de Inocuidad', emoji: '🏆', cat: 'ops', start: '2026-06', end: '2026-07',
    tagline: 'Gamificación de la inocuidad alimentaria',
    desc: 'Competencia interna estilo mundial para reforzar las buenas prácticas de inocuidad entre equipos.',
    stack: ['React', 'Supabase'] },
  { id: 'llamador2', name: 'Mi Gusto Llamador', emoji: '🔔', cat: 'ops', start: '2026-03', end: '2026-04',
    tagline: 'Llamador de pedidos para locales',
    desc: 'Sistema de llamado de pedidos con pantalla para clientes y panel táctil para el mostrador.',
    stack: ['React', 'Supabase'] },
  { id: 'day', name: 'Mi Gusto Day', emoji: '🎉', cat: 'marketing', start: '2026-08', end: '2026-08',
    tagline: 'El día de Mi Gusto',
    desc: 'Experiencia digital para la jornada Mi Gusto Day: promociones, actividades y participación del público.',
    stack: ['React', 'Supabase'] },
];

// Capturas copiadas desde los README de cada proyecto a public/shots/<id>/
const n = (id, count, ext = 'png') => Array.from({ length: count }, (_, i) => `/shots/${id}/${i + 1}.${ext}`);
export const images = {
  orbital: n('orbital', 4), degu: n('degu', 1, 'jpeg'), mes: n('mes', 6), carta: n('carta', 4),
  capa: n('capa', 5), sagrada: n('sagrada', 3), clipper: n('clipper', 4), tech: n('tech', 12),
};

// Proyectos ocultos en la presentación (quitar el id de la lista para volver a mostrarlo)
export const hidden = ['site', 'flamin', 'rooms', 'canjes', 'llamador', 'games', 'golden', 'qr'];

export const sorted = projects
  .filter((p) => !hidden.includes(p.id))
  .sort((a, b) => a.start.localeCompare(b.start));
