// Catálogo completo de proyectos de Mi Gusto
export const categories = {
  web: { label: 'Web & Marca', color: '#ff4d4d', icon: '🌐', desc: 'Sitio oficial, Carta & Plataformas' },
  marketing: { label: 'Marketing & Eventos', color: '#ffb020', icon: '🔥', desc: 'Lanzamientos, 3D, Juegos & Campañas' },
  ops: { label: 'Operaciones & Industria', color: '#3dd6a5', icon: '🏭', desc: 'MES, Planta, BPM & Llamadores' },
  tools: { label: 'Herramientas Internas', color: '#5aa9ff', icon: '🛠️', desc: 'IT, Automatización & Utilidades' },
};

export const projects = [
  // WEB & MARCA
  {
    id: 'site',
    name: 'Mi Gusto Web',
    emoji: '🌐',
    cat: 'web',
    start: '2025-05',
    end: '2026-09',
    tagline: 'Sitio institucional oficial',
    desc: 'Sitio oficial de la marca Mi Gusto con experiencia inmersiva: productos, franquicias, sucursales, empleos y contenido dinámico.',
    stack: ['React', 'GSAP', 'Bootstrap', 'EmailJS', 'Mailchimp'],
  },
  {
    id: 'carta',
    name: 'Carta Digital MG',
    emoji: '📖',
    cat: 'web',
    start: '2025-05',
    end: '2026-09',
    tagline: 'Gestión y sincronización de carta',
    desc: 'Sistema de gestión para actualizar y sincronizar menús, precios y productos al instante en la web de la marca con panel de administración.',
    stack: ['React', 'Firebase', 'Supabase', 'GSAP'],
  },

  // MARKETING & EVENTOS
  {
    id: 'flamin',
    name: "Mi Gusto x Flamin' Hot",
    emoji: '🔥',
    cat: 'marketing',
    start: '2025-11',
    end: '2026-07',
    tagline: 'Lanzamiento y micrositio 3D',
    desc: 'Landing page para la campaña de lanzamiento de la nueva empanada con modelo 3D interactivo, diseño picante y alta conversión.',
    stack: ['React', 'Three.js', 'GSAP', 'Supabase'],
  },
  {
    id: 'influencers',
    name: 'Influencers Form',
    emoji: '🤝',
    cat: 'marketing',
    start: '2025-11',
    end: '2026-09',
    tagline: 'Gestión y auditoría de canjes',
    desc: 'Plataforma para gestión e historial de canjes con influencers, con formulario dinámico configurable, panel admin con PIN y exportación.',
    stack: ['React', 'TypeScript', 'Supabase', 'Tailwind CSS'],
  },
  {
    id: 'crunchy',
    name: 'Validador Promo Crunchy',
    emoji: '✨',
    cat: 'marketing',
    start: '2025-12',
    end: '2026-04',
    tagline: 'Validación de códigos y reservas',
    desc: 'Sistema web en tiempo real para validación de códigos promocionales y DNI para la campaña Crunchy, con consulta de sucursal y fecha de reserva.',
    stack: ['React', 'Supabase', 'Tailwind CSS'],
  },
  {
    id: 'golden',
    name: 'Golden Tickets',
    emoji: '🎫',
    cat: 'marketing',
    start: '2026-02',
    end: '2026-10',
    tagline: 'Fidelización Mi Gusto Lovers',
    desc: 'Sistema para validar tickets premiados, otorgar packs mensuales de empanadas y llevar control seguro de registros y canjes en sucursal.',
    stack: ['React', 'Supabase', 'Framer Motion'],
  },
  {
    id: 'games',
    name: 'Mi Gusto Games',
    emoji: '🕹️',
    cat: 'marketing',
    start: '2026-02',
    end: '2026-04',
    tagline: 'Arcade interactivo para aperturas',
    desc: 'Plataforma de 6 juegos arcade temáticos de empanadas desarrollada para aperturas de sucursales en tótems táctiles, computadoras y celulares.',
    stack: ['Phaser', 'GSAP', 'Howler.js', 'React'],
  },
  {
    id: 'iae',
    name: 'IAE x Mi Gusto',
    emoji: '🏛️',
    cat: 'marketing',
    start: '2026-04',
    end: '2026-06',
    tagline: 'Campaña corporativa & emailing',
    desc: 'Aplicación web que automatiza validación de correos, asignación de códigos únicos de beneficio y envío masivo de emails personalizados en HTML.',
    stack: ['React', 'TypeScript', 'Supabase', 'Tailwind CSS'],
  },
  {
    id: 'degu',
    name: 'Degustación Puertas Cerradas',
    emoji: '🍷',
    cat: 'marketing',
    start: '2026-05',
    end: '2026-05',
    tagline: 'Reserva de eventos VIP en tiempo real',
    desc: 'Plataforma web boutique para reserva y gestión de cupos en tiempo real con diseño premium, animaciones fluidas y sincronización instantánea.',
    stack: ['React', 'TypeScript', 'GSAP', 'Tailwind CSS', 'Supabase'],
  },
  {
    id: 'sagrada',
    name: 'Mi Gusto x La Sagrada',
    emoji: '🍺',
    cat: 'marketing',
    start: '2026-05',
    end: '2026-06',
    tagline: 'Colaboración y experiencia digital',
    desc: 'Micrositio promocional de la colaboración con estética premium, animaciones fluidas y registro exclusivo.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'GSAP', 'Supabase'],
  },
  {
    id: 'roulette',
    name: 'Ruleta de Premios Aperturas',
    emoji: '🎡',
    cat: 'marketing',
    start: '2026-07',
    end: '2026-08',
    tagline: 'Gamificación y captación de clientes',
    desc: 'Aplicación web interactiva para capturar datos de clientes en inauguraciones y ofrecer una ruleta de premios con animaciones dinámicas.',
    stack: ['React', 'Vite', 'Tailwind CSS', 'GSAP', 'Supabase'],
  },
  {
    id: 'day',
    name: 'Mi Gusto Day',
    emoji: '🎉',
    cat: 'marketing',
    start: '2026-08',
    end: '2026-08',
    tagline: 'Landing de captación & cupones',
    desc: 'Landing page con formulario inteligente que recolecta datos de usuarios y envía automáticamente cupones de descuento para fidelización.',
    stack: ['React', 'Tailwind CSS', 'Supabase'],
  },

  // OPERACIONES & INDUSTRIA
  {
    id: 'lolla',
    name: 'Lollapalooza Order Caller',
    emoji: '📣',
    cat: 'ops',
    start: '2026-02',
    end: '2026-03',
    tagline: 'Sistema offline para eventos masivos',
    desc: 'Sistema offline para puntos de venta en Lollapalooza: interfaz táctil para armado de pedidos y pantalla vertical para retiro de clientes sin conexión.',
    stack: ['React', 'Supabase', 'Offline Sync', 'Local Storage'],
  },
  {
    id: 'ordercaller',
    name: 'Order Caller Locales',
    emoji: '🔔',
    cat: 'ops',
    start: '2026-03',
    end: '2026-05',
    tagline: 'Llamador de pedidos para sucursales',
    desc: 'Sistema de llamado de pedidos local que automatiza la gestión de órdenes del staff, organizando y notificando pedidos en tiempo real.',
    stack: ['React', 'Supabase', 'WebSockets'],
  },
  {
    id: 'mes',
    name: 'MES System MG',
    emoji: '🏭',
    cat: 'ops',
    start: '2026-03',
    end: '2026-06',
    tagline: 'Manufacturing Execution System',
    desc: 'Digitalización de producción en planta: monitoreo en tiempo real de máquinas, seguimiento de órdenes, conversor de datos y reportes analíticos.',
    stack: ['React', 'Supabase', 'Recharts', 'Tailwind CSS'],
  },
  {
    id: 'orbital',
    name: 'MG Orbital',
    emoji: '🛰️',
    cat: 'ops',
    start: '2026-03',
    end: '2026-10',
    tagline: 'Digitalización industrial y logística',
    desc: 'Ecosistema para planta: control en tiempo real de logística y camiones por GPS, stock de materias primas, reportes de calidad y auditorías.',
    stack: ['React', 'Supabase', 'Leaflet', 'Chart.js'],
  },
  {
    id: 'copa',
    name: 'Copa Mundial de Inocuidad',
    emoji: '🏆',
    cat: 'ops',
    start: '2026-06',
    end: '2026-07',
    tagline: 'Gamificación de inocuidad alimentaria',
    desc: 'Juego interactivo de trivia por fases, animaciones, ranking y pergamino de compromiso para promover buenas prácticas y trabajo en equipo.',
    stack: ['React', 'Tailwind CSS', 'Supabase', 'Canvas Confetti'],
  },
  {
    id: 'capa',
    name: 'MG Capacitaciones',
    emoji: '🎓',
    cat: 'ops',
    start: '2026-06',
    end: '2026-09',
    tagline: 'Capacitaciones de fábrica & BPM',
    desc: 'Plataforma web interna para capacitaciones de fábrica con cursos interactivos y temas operativos, diseñada para desktop y mobile.',
    stack: ['React', 'TypeScript', 'Supabase', 'Tailwind CSS'],
  },

  // HERRAMIENTAS INTERNAS
  {
    id: 'rooms',
    name: 'Reminders Rooms',
    emoji: '🗂️',
    cat: 'tools',
    start: '2025-11',
    end: '2026-02',
    tagline: 'Recordatorios colaborativos por salas',
    desc: 'Aplicación colaborativa con vistas de Tarjetas, Calendario y Gantt, analíticas, notificaciones y sincronización en tiempo real.',
    stack: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Supabase'],
  },
  {
    id: 'qr',
    name: 'QR Generator Pro',
    emoji: '🔳',
    cat: 'tools',
    start: '2026-02',
    end: '2026-08',
    tagline: 'Generador web de códigos QR',
    desc: 'Generador de códigos QR de alta calidad con personalización avanzada, duración ilimitada y gestión centralizada de historial.',
    stack: ['React', 'TypeScript', 'Tailwind CSS'],
  },
  {
    id: 'tech',
    name: 'TechControl',
    emoji: '💻',
    cat: 'tools',
    start: '2026-05',
    end: '2026-10',
    tagline: 'Gestión de activos IT y compras',
    desc: 'Plataforma integral para gestión, auditoría y control centralizado de activos IT, impresoras, cartelería digital, guardias y pedidos de compras.',
    stack: ['React', 'TypeScript', 'Tailwind CSS', 'Supabase'],
  },
  {
    id: 'massivemail',
    name: 'Massive Mail Sender',
    emoji: '📧',
    cat: 'tools',
    start: '2026-06',
    end: '2026-08',
    tagline: 'Desktop app para envíos masivos',
    desc: 'Aplicación de escritorio en Python con editor visual HTML, imágenes inline, plantillas e importación desde Excel, CSV, PDF y Sheets.',
    stack: ['Python', 'CustomTkinter', 'SMTP', 'Pandas'],
  },
  {
    id: 'multimail',
    name: 'Multi Mail Sender',
    emoji: '📨',
    cat: 'tools',
    start: '2026-06',
    end: '2026-09',
    tagline: 'Envíos personalizados multi-servidor',
    desc: 'App de escritorio moderna y liviana para envíos masivos con gestión de listas, editor enriquecido, firmas y soporte multi-SMTP (Ferozo, Gmail, Outlook).',
    stack: ['Python', 'Tkinter GUI', 'SMTP', 'HTML Editor'],
  },
  {
    id: 'screenflow',
    name: 'ScreenFlow',
    emoji: '🎬',
    cat: 'tools',
    start: '2026-07',
    end: '2026-09',
    tagline: 'Editor de video local en navegador',
    desc: 'Editor de video interactivo 100% en el navegador: recorte de tramos con línea de tiempo y miniaturas, rotación, velocidad y conversión a Video Wall.',
    stack: ['React', 'Vite', 'Canvas', 'Web Audio API'],
  },
  {
    id: 'translate',
    name: 'Real Time Translate',
    emoji: '🌐',
    cat: 'tools',
    start: '2026-08',
    end: '2026-10',
    tagline: 'Traductor simultáneo con voz y audio',
    desc: 'App web de traducción simultánea que captura voz por Web Speech API, traduce en tiempo real con fallback inteligente y sintetiza en audio natural.',
    stack: ['React', 'Web Speech API', 'Speech Synthesis', 'Tailwind CSS'],
  },
  {
    id: 'autoanswers',
    name: 'Auto Mail Answers',
    emoji: '🤖',
    cat: 'tools',
    start: '2026-09',
    end: '2026-10',
    tagline: 'Respuesta automática & monitoreo',
    desc: 'Aplicación de escritorio con GUI moderna para respuesta automática y monitoreo continuo de correos con prevención de duplicados.',
    stack: ['Python', 'IMAP/SMTP', 'Threading', 'GUI'],
  },
];

// Capturas copiadas en public/shots/<id>/
const n = (id, count, ext = 'png') => Array.from({ length: count }, (_, i) => `/shots/${id}/${i + 1}.${ext}`);

export const images = {
  orbital: n('orbital', 4),
  degu: n('degu', 1, 'jpeg'),
  mes: n('mes', 6),
  carta: n('carta', 4),
  capa: n('capa', 5),
  sagrada: n('sagrada', 3),
  screenflow: n('clipper', 4),
  clipper: n('clipper', 4),
  tech: n('tech', 12),
};

// Proyectos ordenados cronológicamente por fecha de inicio
export const sorted = [...projects].sort((a, b) => a.start.localeCompare(b.start));

